version: "3"

services:

  db:
    image: mysql/mysql-server:8.0
    # read_only: true
    restart: unless-stopped
    volumes:
      - ./volumes/db/var/lib/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_USER=mattermost
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=mattermost
    # uncomment the following to enable backup
      - AWS_ACCESS_KEY_ID=AKIA4QAQQ22K3DMDIF7H
      - AWS_SECRET_ACCESS_KEY=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
      - WALE_S3_PREFIX=s3://bitsbeat/new
      - AWS_REGION=ap-southeast-1

  app:
    build:
      context: app
      # uncomment following lines for team edition or change UID/GID
      args:
        - edition=team
        - PUID=1000
        - PGID=1000
    restart: unless-stopped
    volumes:
      - ./volumes/app/mattermost/config:/mattermost/config:rw
      - ./volumes/app/mattermost/data:/mattermost/data:rw
      - ./volumes/app/mattermost/logs:/mattermost/logs:rw
      - ./volumes/app/mattermost/plugins:/mattermost/plugins:rw
      - ./volumes/app/mattermost/client-plugins:/mattermost/client/plugins:rw
      - /etc/localtime:/etc/localtime:ro
      # When you want to use SSO with GitLab, you have to add the cert pki chain of GitLab inside Alpine
      # to avoid Token request failed: certificate signed by unknown authority (link: https://github.com/mattermost/mattermost-server/issues/13059)
      # - <path_to_your_gitlab_pki>/pki_chain.pem:/etc/ssl/certs/pki_chain.pem:ro
    environment:
      # set same as db credentials and dbname
      - DB_PORT_NUMBER=3306
      - MM_SQLSETTINGS_DRIVERNAME=mysql
      - MM_USERNAME=mattermost
      - MM_PASSWORD=123456
      - MM_DBNAME=mattermost

      # use the credentials you've set above, in the format:
      # MM_SQLSETTINGS_DATASOURCE=${MM_USERNAME}:${MM_PASSWORD}@tcp(db:3306)/${MM_DBNAME}?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s
      - MM_SQLSETTINGS_DATASOURCE=mattermost:R00t123456@tcp(db:3306)/mattermost?charset=utf8mb4,utf8&readTimeout=30s&writeTimeout=30s

      # in case your config is not in default location
      - MM_CONFIG=/mattermost/config/config.json

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    read_only: true
    restart: unless-stopped
    volumes:
      # This directory must have cert files if you want to enable SSL
      - ./volumes/web/cert:/cert:ro
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/web/nginx.conf:/etc/nginx.conf:ro
